name: stepcompare
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  provider: ^6.0.2
  health: ^3.4.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  flutter_hooks: ^0.18.3
  shared_preferences: ^2.0.12
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true